# Generated by Django 5.2.4 on 2025-08-06 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['student', 'year'], name='report_card_student_456f21_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['term'], name='report_card_term_1ef0b0_idx'),
        ),
    ]
