# Generated by Django 5.2.4 on 2025-08-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0002_reportcard_report_card_student_456f21_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='overall_average',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='subject_averages',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
