# Generated by Django 5.2.4 on 2025-08-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0003_reportcard_overall_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='task_status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In Progress'), ('NOT_STARTED', 'Not Started')], default='NOT_STARTED', max_length=20),
        ),
    ]
