# Generated by Django 3.2.7 on 2022-01-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_auto_20220130_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
    ]
