# Generated by Django 3.2.7 on 2022-02-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_profilefeeditem_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefeeditem',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
