# Generated by Django 5.1.1 on 2024-10-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, error_messages={'max_length': 'Book name is too long.', 'unique': 'Book with this name already exists.'}, help_text='Book name', max_length=100, null=True),
        ),
    ]
