# Generated by Django 5.1.1 on 2024-09-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('A', 'Author'), ('E', 'Editor')], default='E', max_length=1),
        ),
    ]
