# Generated by Django 5.2.4 on 2025-08-07 02:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0002_initial'),
        ('report_card', '0002_reportcard_report_card_student_456f21_idx_and_more'),
        ('subject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={},
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['report_card'], name='mark_mark_report__412f86_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['subject'], name='mark_mark_subject_71872e_idx'),
        ),
    ]
