# Generated by Django 5.1.1 on 2024-10-05 03:37

import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(storage=polls.models.select_storage, upload_to=''),
        ),
    ]
